name: ParkIt CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. El robot descarga una copia de tu código de GitHub
      - name: Descargar código
        uses: actions/checkout@v3

      # 2. El robot instala Node.js en su entorno virtual
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. El robot instala las dependencias para probar que no haya errores
      - name: Instalar dependencias
        run: npm install

      # 4. El robot compila la imagen de Docker usando tu Dockerfile
      - name: Construir imagen de Docker
        run: docker build -t parkit-backend:latest .
